Repository Sriparno08/Openpedia, pull requests merged in 2024-08, with the labels that each got.

#452 Placed the Header title within the header image in page introduction-…
  client/pages/introduction-to-open-source/index.html
  client/pages/introduction-to-open-source/styles.css
Labels: ui

#454 converted open source program from static to dynamic
  client/pages/open-source-programs/app.js
  client/pages/open-source-programs/index.html
  client/pages/open-source-programs/styles.css
Labels: chore

#456 Changes2
  .vscode/settings.json
  client/pages/introduction-to-open-source/app.js
  client/pages/introduction-to-open-source/index.html
  client/pages/introduction-to-open-source/styles.css
Labels: ui

#457 [Enhancement] - Improvement on about and contribution cards ui and reverted changes in Landing Page #451
  client/app.js
  client/globals.css
  client/index.html
  client/styles.css
  package.json
Labels: ui

#458 changed incorrect path pattern
  client/components/footer.js
  client/index.html
Labels: chore

#459 Added Card UI in page Introduction to Open Source
  .gitignore
  client/assets/arrow.svg
  client/assets/open-link-arrow.svg
  client/assets/openlink-arrow.png
  client/pages/introduction-to-open-source/app.js
  client/pages/introduction-to-open-source/index.html
  client/pages/introduction-to-open-source/styles.css
Labels: ui

#463 Learn Git and GitHub
  client/pages/learn-git-and-github/app.js
Labels: ui

#465 Updated the GitHub-Get Started Resource in README.md
  README.md
Labels: documentation

#467 Updated Four more Open Source programs in README.md
  README.md
Labels: documentation

#469 Changed the hover color of category to its initial color in dark mode
  client/styles.css
Labels: ui

#472 Responsive Hero Section in Home Page
  client/styles.css
Labels: ui

#471 Added flutter into the Beginner-Friendly Repositories section in README.md
  README.md
Labels: resource

#480 Responsive Category Section 2
  client/styles.css
Labels: ui

#490 Removed Streach of Hero in beginner Friendly Repo
  client/pages/beginner-friendly-repos/styles.css
Labels: ui

#492 Made Introduction to Open Source Page Responsive
  client/pages/introduction-to-open-source/styles.css
Labels: ui

#496 Changed Hero Section in Introduction to open source(responsive)
  client/pages/introduction-to-open-source/styles.css
Labels: ui

#497 Dark mode for Introduction to Open Source Page
  client/pages/introduction-to-open-source/app.js
  client/pages/introduction-to-open-source/styles.css
Labels: ui

#498 Changed ui of box1 in introduction to open source
  client/pages/introduction-to-open-source/styles.css
Labels: ui

#499 Changed Head Text to align in middle and increased font size in intoduction to open source
  client/pages/introduction-to-open-source/styles.css
Labels: ui

#500 Dark mode for Open Source Programs Page
  client/pages/open-source-programs/app.js
Labels: ui

#503 Changed Hero section in open source programs
  client/pages/open-source-programs/styles.css
Labels: ui

#504 Normalised card hide and added spacing in open source programs
  client/pages/open-source-programs/styles.css
Labels: ui

#505 Changed Hero in learn git and github
  client/pages/learn-git-and-github/index.html
  client/pages/learn-git-and-github/styles.css
Labels: ui

#506 Changed Hero in learn git and github (responsive)
  client/pages/learn-git-and-github/styles.css
Labels: ui

#507 Normalised card height and added spacing in open source programs (responsive)
  client/pages/open-source-programs/styles.css
Labels: ui

#508 UI enhancemnet
  client/pages/contributing-to-open-source/app.js
  client/pages/contributing-to-open-source/styles.css
  client/pages/introduction-to-open-source/index.html
  client/pages/learn-git-and-github/app.js
  client/pages/learn-git-and-github/styles.css
Labels: ui
